import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import DarkThemeProvider from "@/services/DarkThemeProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkThemeProvider>
          <Header />
          <section className="max-w-6xl mx-auto ">{children}</section>
        </DarkThemeProvider>
      </body>
    </html>
  );
}
